### ISSUE TITLE
MSSQL connector has SSL support for the Secretless-to-server connection

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1032]
At current the Secretless-to-server connection for the MSSQL connector does not support SSL. In this effort, we will enable support for configuring the MSSQL connector with support for SSL in the Secretless-to-Server connection.

## Acceptance criteria
- [ ] Update the MSSQL connector to support the same level of SSL as the MySQL and PostgreSQL connectors do at current
- [ ] Update the supported config for the MSSQL connector to include SSL config parameters

## Implementation overview
At present the driver will use encryption if it is available on the server-side. The plan here is to provide more explicit control of encryption.

### TLS Support interface in Secretless

All database connectors use the same Secretless configuration parameters to configure the Secretless connector to connect to the backend server using TLS.

The Secretless configuration parameters for TLS that will be supported in this epic for the MSSQL connector include:

+ `sslmode`
  This option determines if the connection between Secretless Broker and your database is protected by SSL.

  Supported values are:
  + `disable`: Only try a non-SSL connection.
  + `require`: Only try an SSL connection.
  + `verify-ca`: Only try an SSL connection, and verify that the server certificate is issued by a trusted certificate authority (CA)
+ `sslrootcert`
  The content of this parameter specifies the SSL certificate authority (CA) certificate(s) in PEM format. If present, the server’s certificate will be verified to be signed by one of these authorities.
+ `sslcert` **(not supported for this connector)** 
  The content of this parameter specifies the client SSL certificate in PEM format. This parameter is ignored if an SSL connection is not made. Corresponds to `ssl-cert`.
+ `sslkey` **(not supported for this connector)** 
  The content of this parameter specifies the secret key used for the client certificate. This parameter is ignored if an SSL connection is not made. Corresponds to ssl-key.

### MSSQL Considerations

Microsoft documents its SQL Server encryption options [here](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15).

In Secretless, we use a [Golang MSSQL driver](https://github.com/cyberark/go-mssqldb) supports the following options for TLS:

1. Encryption is available but off. This tells the server that if it has TLS then the client is happy to use it,
    otherwise it’s fine. (**not supported in this effort, since we don’t currently support the `sslmode`
    `allow` or `prefer` modes in the Secretless configuration** )
2. Encryption is available and on. This tells the server that the client expects to use encryption, and
    trusts the server certificate without verification. (e.g. `sslmode` is `require`).
3. Encryption is not available. This tells the server to not use TLS. (e.g. `sslmode` is `disable`)

In this effort we add support to Secretless for modes (2) and (3). In addition, we will add support for a fourth mode for MSSQL (`verify-ca`) that is similar to (2), where the client expects to use encryption AND wants to connect only to a trusted server (e.g. `sslmode` is `verify-ca` and `sslrootcert` is supplied).

### Design
- There is a plan for adding TLS support for the MSSQL connector (#1153)

### Core implementation tasks

Ideally each story  would come with its own set of test cases so that the testing story concludes as the other stories are finished.

- Initial support for sslmode. For this issue the only value can be `disable`, which means no TLS. (#1163)
- Connector supports additional ssl options (#1186)
- Support for sslmode `require` so that TLS must be used. (#1164)
- Support for sslmode `verify-ca`, + sslrootcert, so that TLS must be used and the server certificate must be verified. (#1165)
- ~Support for specifying client certificate (#1166)~
- Unit/Integration tests for each sslmode and specifying client certificate (part of each task above, but a final review in #1167)

### Beyond implementation tasks

- Update connector documentation to reflect TLS support (cyberark/secretless-docs#246)
- Update troubleshooting to reflect issues surrounding use of TLS support (#1169)
- MSSQL connector with SSL support has undergone XA (#1170)
- MSSQL connector TLS support has undergone security review (#1195)

### Additional tech debt tasks included in this epic
- Review trivy output in Jenkins for quickstart container (#1175)
- Review trivy output in Jenkins for redhat container (#1176)
- Credentials should be zeroized immediately after connection is made (#1188)

**Comment by izgeri** [comment]
@alexkalish we've added a draft plan to the epic above - would you like us to include a project brief? maybe this is a good test case for creating a markdown-based template for it?

**Comment by alexkalish** [comment]
@izgeri: Bunch of questions/comments:
1. Reading the docs MySQL and PG, it appears that SB has adopted the PG configuration options for all DB connectors.  Is that correct?  Are we creating a consistent configuration options across DB connectors?  This is mentioned in the linked design spike, but would be good restate here.
2. Under AC, I do think that it would be good to specify the exact level of support being added, instead of comparing it to other connectors.  What features are supported and not supported, specifically?
3. Does this need a security review or was that part of the conversation that already happened with @andytinkham?
4. I know that performance testing is more a GA DoD item, but will any performance testing be part of this project?
5. What about XA?

**Comment by izgeri** [comment]
@alexkalish -

1. Yes, we have the same config for SSL across all connectors. I mentioned this to Andy yesterday - we made this choice in the hope that it makes it easier to set up Secretless, and we are careful in our documentation to make the connection between our configuration parameters and the database server's typical parameters (if different). I've added this to the epic description.
1. I'm actually not sure what you feel is missing from the epic description on this - I looked over the `MSSQL Considerations` and added a question for @doodlesbykumbi to clarify, hopefully these changes taken together will clarify this point.
1. Andy did not raise this, though we did talk extensively about the testing we'll have related to security. @andytinkham can you let us know if you want me to add a card for security review for this feature?
1. No performance testing will be part of this project
1. There is an XA card (#1170) - it's not well defined yet, we'll define it during the epic. I'd be glad for your feedback on that :)

**Comment by alexkalish** [comment]
@izgeri:

1. ✅ 
2. I see your point.  Considerations does have more details.  I do have one question: Based on the language in that section, it's not 💯 clear to me that setting `sslmode: require` would result in the SB to SQL Server connection failing if TLS fails.  Can you confirm?
3. Will wait for Andy's response.
4. Understood.  I looked after posting and some performance testing is part of the beta level, but I'm okay with leaving it out for now.
5. Ah!  Thanks!  I had just been looking at the list of issues in the description (as opposed to the connected issues) and it wasn't there.

**Comment by izgeri** [comment]
👍 

so @doodlesbykumbi I think what remains is to you -
- [ ] confirm that setting sslmode: require would result in the SB to SQL Server connection failing if TLS fails
- [ ] update the `MSSQL considerations` section to be clearer about which modes will be supported by Secretless at the end of each epic, and which Secretless config params will be required to run with each mode

**Comment by doodlesbykumbi** [comment]
>  confirm that setting sslmode: require would result in the SB to SQL Server connection failing if TLS fails.

In the other DBs I think this only fails if sslrootcert is set, otherwise `InsecureSkipVerify` is used. This is something that perhaps needs revisiting.

**Comment by izgeri** [comment]
Note that @doodlesbykumbi found this reference:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/076e0764-576f-40a9-9bfc-b622e4ac8e22/sql-2014-certificate-authentication?forum=sqlsecurity

> SQL Server does not support mutual authentication via TLS. In other words, there is no certificate based client authentication available in SQL Server.

As such, we will not be doing #1166 in this effort, since it is not relevant for MSSQL.

**Comment by andytinkham** [comment]
For a security review, I think it's good to have one at the end just to make sure we caught any deviations from plan. I'd normally consider it a quick conversation though - I think we addressed everything up front, and will try to cover deviations from plan as they arise, but one last, "yep, this is good" is probably a good thing.

**Comment by izgeri** [comment]
Note:

We learned today that it may be easier to add support for `verify-full` to this connector than it is to add support for `verify-ca`. Here are my notes:

Secretless SSL mode configuration options:
- `require` - the client wants a secure connection, but it doesn’t care about verifying anything about the server. the connection will fail if the server does not support an encrypted connection.
- `verify-ca` - like `require`, but additionally the client will verify the server Certificate Authority (CA) certificate against the configured CA certificates (provided in the Secretless config via `sslrootcert`). The connection attempt fails if no valid matching CA certificates are found.
- `verify-full` - like `verify-ca`, but additionally perform host name identity verification by checking the host name the client uses for connecting to the server (provided in the Secretless config via `host`) against the identity in the certificate that the server sends to the client. The connection fails if there is a mismatch. For encrypted connections, this option helps prevent man-in-the-middle attacks.  Check whether the host name matches using the standard logic here: https://golang.org/src/crypto/x509/verify.go?s=31362:31414#L996 - ie compare to Common Name and Subject Alternate Names
- `verify-full` with the option to override the expected server certificate host value with a Secretless parameter `hostInCertificate`

At current:
- MySQL connector supports `require` and `verify-ca`
- PostgreSL connector supports `require` and `verify-ca`
- MSSQL connector supports `require` and `verify-full`

For this epic, we will consider whether we want to:
1. add `verify-full` support to pg/msyql (may be able to leverage standard `crypto/tls` golang library to implement)
1. add `verify-ca` support to mssql
1. add `verify-full` with the ability to override the server host value to mssql (the driver we use supports this)

Note: we also want to add an spike to investigate how secretless would handle server TLS renegotiation - upon review, it is not clear right now.
