### ISSUE TITLE
Broker can delegate basic sanity checks on `credentials` keys to plugins

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#1065]
Currently the broker does not do any early checking on `credentials` configuration. This causes problems in the UX as it defers obvious problem elevation until a much later time than needed.

Example config that should not allow the broker to start without error:
```yaml
version: 2
services:
  mysql-socket:
    connector: mysql
    listenOn: tcp://127.0.0.1:3307
    credentials:
      lol: foo
```

AC:
- [ ] Broker can delegate plugin-specific `configurations` checking to the plugin over APIs
- [ ] Broker exits with these errors when a plugin indicates that an invalid configuration was attempted
- [ ] TBD: Upgrade internal plugins to do basic key checking on required params
- [ ] TBD: Upgrade internal plugins to show warnings on likely needed (but optional) credential keys
