### ISSUE TITLE
Cleanup handler plugin API

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#109]
We did not clean up things with the plugin API yet as well as we should.

AC:
- [ ] Handlers don't need Authorize or LoadKeys method
- [ ] Handlers have minimal set of (or have cleaned up) fields
- [ ] Connection managers use the same constructor as handlers/listeners
- [ ] EventNotifier should ideally be fully in the plugin manager.

**Comment by izgeri** [comment]
This issue is moot after the recent changes - closing the issue now.
