### ISSUE TITLE
There is a stable Secretless MSSQL connector 

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1161]
- (optional) Secretless has e2e tests with MSSQL in a K8s environment
- [ ] Secretless with MSSQL has a comprehensive security review (covered by #1195 in epic #1032)
- [ ] Secretless with MSSQL has run stability tests (#1218)
- [ ] Secretless with MSSQL has run performance tests (#1216)
- (optional) Evaluate whether additional troubleshooting scenarios should be documented
- [ ] Remove the `beta` label from the MSSQL connector in the documentation (cyberark/secretless-docs#247)
- (optional) Secretless MSSQL connector has been refactored to improve performance

**Comment by boazmichaely** [comment]
@alexkalish - what is the effort remaining here for GA?
- Is a security review scheduled for @andytinkham? (now that TLS is done) ?
- Evaluate whether additional troubleshooting scenarios should be documented: This should not hold up GA
- performance test seems to be in progress?

In summary can we get an update on the scope and effort? The reason for this information is in order to confirm that this should be the next task as planned

**Comment by andytinkham** [comment]
Initial security review meeting is scheduled for later this morning.

**Comment by izgeri** [comment]
I also question whether we need an e2e test with MSSQL in a k8s env. We already test Secretless extensively in a K8s env, and we have integration tests for MSSQL in a docker-compose env. I'm not sure what additional validation we'll be achieving by adding this e2e test for each new connector.

@andytinkham I'd love your feedback on this.

**Comment by andytinkham** [comment]
Other than providing a realistic customer-like scenario, I agree that I'm not sure what additional value an e2e test would add. As I understand it, there's nothing specific to k8s in the MSSQL connector - once the creds are injected, it's just a pipe. If I suggested this test earlier, I don't remember my reasoning for doing so.  I'm ok with omitting it.
