### ISSUE TITLE
Secretless works with Conjur Kubernetes authenticator

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#248]
There is an easy way to deploy Secretless in Kubernetes so that it can automatically authenticate with Conjur leveraging the existing Conjur Kubernetes authenticator.

- [x] Parent of #243 - Conjur provider can use authenticator client to get access token
- [x] Parent of #250 - Website has a tutorial for Conjur + Secretless in Kubernetes
- [x] Parent of #252 - Website documents migration path from K8s Secrets to Conjur as the credential provider
- [x] Parent of #254 -  Kubernetes demo has a version that uses the Conjur credential provider with the Conjur Kubernetes authenticator
- [x] Parent of #322 - Website Conjur-in-K8s tutorial uses the Conjur-K8s authenticator to authenticate with Conjur
- [x] Parent of #340 -  Conjur handler uses the Conjur-K8s authenticator
- [x] Parent of https://github.com/conjurdemos/kubernetes-conjur-demo/issues/17 - Kubernetes demo has Secretless flow
- [x] Parent of https://github.com/conjurdemos/kubernetes-conjur-demo/issues/12 - Kubernetes demo uses `cyberark/demo-app` (required update to get the demo working with Secretless)

**Comment by izgeri** [comment]
Added links to stories for updating `conjurdemos/kubernetes-conjur-demo`
