### ISSUE TITLE
Secrets do not remain in the sidecar memory

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#249]
Ensure secrets do not remain in the sidecar memory - should be cleaned

- [X] Parent of #269 - Zeroize http credentials after use
- [ ] Parent of #270 - SSH agent only keeps loaded keys for the duration of connection
- [ ] Parent of #271 -  Proposal for ensuring that all credentials are manually zeroized after use
- [ ] Parent of #617 - Credentials are consistently zeroized after use

**Comment by izgeri** [comment]
@sgnn7 can you do an updated status on this at some point? if you're not free, lmk - I am asking only bc you were the last to work on this. I'd like to figure out what remains to do

**Comment by sgnn7** [comment]
I don't think anything changed from https://github.com/cyberark/secretless-broker/issues/249#issuecomment-410713128 since I last worked on it. Work that needs to be done is the delta between that and what level of zeroization we want (just clearing the vars or zeroizing as well)
