### ISSUE TITLE
Secretless configuration can be specified using K8s CRDs

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#343]
## Objective
At current the Secretless configuration must be specified in a YAML file that is loaded into the Secretless container, usually via ConfigMaps.
With this change, the Secretless configuration can be loaded into a K8s custom resource definition before the sidecar is deployed, and the Secretless sidecar can reference the relevant CRD in its manifest. 

Background on CRDs:
https://github.com/yaronha/kube-crd
https://github.com/kubernetes/code-generator

## Story Breakdown

- [x] Parent of #368 - CRD configuration plugin is tested
- [x] Parent of #355 - CRDs spike
- [x] Parent of #356 - CRDs usable in Secretless Broker
- [ ] Parent of #365 - CRD documentation
- [ ] Parent of #368 - CRD plugin test
- [x] Parent of #389 - CRD injector fix

**Comment by sgnn7** [comment]
Another info page on this: https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/

**Comment by izgeri** [comment]
Duplicate of #836
