### ISSUE TITLE
Broker has no tech debt

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#377]
# Updates to test suites

## Adding tests
- [ ] Parent of #82 - AWS handler has test suite with documentation
- [ ] Parent of #411 - Kubernetes Secrets provider has integration tests
- [ ] Parent of #483 - PostgreSQL handler protocol has unit tests
- [ ] Parent of #156 - All demos are tested through the "test" build step on Jenkins

## Improving test workflows
- [ ] Parent of #162 - Remove all dependencies on non-basic Docker images
- [ ] Parent of #321 - Test suite docker-compose runs are namespaced to avoid collisions

**Comment by izgeri** [comment]
We're tracking the tech debt using the label now, so this epic is no longer needed.
