### ISSUE TITLE
Broker use cases besides Kubernetes are well documented

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#378]
- [ ] Parent of #86 - Instructions are available for using Secretless on Mac for SSH and Conjur proxy
- [ ] Parent of #87 - Instructions are available for using Secretless on a Jenkins executor for SSH and AWS proxy
- [ ] Parent of #88 - Add non-docker example usage to docs

**Comment by izgeri** [comment]
This issue was moved to cyberark/secretless-docs#89
