### ISSUE TITLE
Broker website UX is improved

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#408]
- [ ] Parent of #352 - Take inventory of mobile fixes needed
- [x] Parent of #434 - Style updates for homepage and blog listing
- [ ] Parent of #307 - The link-checker for the website doesn't require .html extension

**Comment by jtuttle** [comment]
Closing as stale, the future of these docs is uncertain.
