### ISSUE TITLE
Website feedback from technical writer / PM has been addressed

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#412]
Critical items for beta release:
- [x] Parent of #413 - Website security page is improved
- [x] Parent of #414 - Website "How it Works" is updated to be more clear
- [x] Parent of #415 - Website feature descriptions are improved
- [x] Parent of #422 - Website "Why Secretless?" page is consistent with rest of site
- [x] Parent of #454 - Security page has fixes from Perry

Additional items, to be completed ASAP:
- [x] Parent of #423 - Website main page architecture diagrams have better style
- [x] Parent of #416 - Website quick start on main page shows results
- [x] Parent of #417 - Website Kubernetes tutorial is more clearly labeled
- [x] Parent of #418 - Website plugins page parses markdown properly
- [x] Parent of #431 - Go mod blog post is updated to match new Golang version
