### ISSUE TITLE
Secretless supports deploying to OpenShift

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#453]
Deployment works in OpenShift, and any changes that need to be made to get it to work are documented.

# Getting Secretless working end-to-end in OC with Postgres
- [x] Parent of https://github.com/conjurdemos/kubernetes-conjur-demo/issues/23 - OpenShift demo uses `cyberark/demo-app`
- [x] Parent of #582 - Update conjur-api-go dependency
- [x] Parent of cyberark/conjur-api-go#39 - LoadConfig method to get current user errors in OpenShift
- [x] Parent of conjurdemos/kubernetes-conjur-demo#42 - Secretless + PostgreSQL flow uses SSL

# Automating demo
- [x] Parent of conjurdemos/kubernetes-conjur-demo#43 - Demo is updated to run automated tests against OC cluster
- [x] Parent of conjurdemos/kubernetes-conjur-demo#49 - Script 7 waits for app pods to avoid flaky tests

# Getting Secretless working end-to-end in OC with MySQL
- [x] Parent of conjurdemos/pet-store-demo#10 - Demo app is updated to allow option of using with MySQL database
- [x] Parent of conjurdemos/kubernetes-conjur-demo#44 - Demo is updated to have end-to-end-flow of Secretless with MySQL  (configured for SSL)

# Documentation
- [ ] Parent of cyberark/secretless-docs#80 - Documentation describes supported versions of Conjur, K8s, and OC
- [ ] Parent of  cyberark/secretless-docs#81 - Documentation describes deploying to OC
