### ISSUE TITLE
A plan exists for updating the database handlers to use SSL for the backend connections

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#460]
This story should be used to plan out how the PostgreSQL and MySQL handlers will be updated to enable communication with the backends via SSL. It will likely involve:

- [x] Digging into the handler code to understand how each of them currently works
- [x] Researching how MySQL clients typically implement SSL in the client-to-backend connection (the [MySQL protocol docs](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_v10.html) may be helpful)
- [x] Researching how PostgreSQL clients typically implement SSL in the client-to-backend connection (the [PostgreSQL SSL docs](https://www.postgresql.org/docs/9.3/static/ssl-tcp.html) may be helpful)
- [x] Looking for OSS libraries (esp. in golang) that we can leverage in building this functionality (for example, the [Google CloudSQL Proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy) probably has some useful info)

The end result should be a solid plan for the path forward.

Plan: [Downstream-TLS-Support-for-Database-Handlers](https://github.com/cyberark/secretless-broker/wiki/Downstream-TLS-Support-for-Database-Handlers)

**Comment by doodlesbykumbi** [comment]
## TLS Support for Database Handlers

### General approach
+ Extract sslmode params from credentials into backend connection options
+ Dial backend to get net.Conn
+ Default to insecure connection, regardless of support
+ Ensure client TLS requirements match server requirements and support, FAIL if not.
  + Default to insecure connection, regardless of support
  + Use TLS if server demands it
+ Upgrade net.Conn to tls.Conn and use appropriate strategy for sslmode

### Test cases

Given DB container services with TLS support and without:
+ each sslmode works or errors as intended
+ happy path to secretless via unix socket, and tcp

### TODO

+ update documentation for each db handler with descriptions of sslmode params in credentials

## MySQL
https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html#using-encrypted-connections-client-side-configuration

### Handshake

https://dev.mysql.com/doc/internals/en/connection-phase.html

Note that throughout the handshake a sequenceID is maintained which is incremented at every step. This means a handshake with TLS-encryption will have a final sequenceID higher than a plain handshake.

1. Upon initial Dial the server responds to client with capabilities
2. Client creates HandshakeResponse with capabilities in common .e.g TLS
3. To initiate an TLS-encrypted connection the client sends an SSLRequest, a truncated version of HandshakeResponse. See https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::SSLRequest
4. Finally, client sends HandshakeResponse which contains authentication information. See https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
5. Deal with Authentication Method Mismatch. See https://dev.mysql.com/doc/internals/en/authentication-method-mismatch.html

### Implementation

support for "ssl-mode" = (
  DISABLED
  PREFFERED
  REQUIRED
  VERIFY_CA
  VERIFY_IDENTITY
)

### OSS libraries

+ https://github.com/go-sql-driver/mysql/blob/master/packets.go#L322-L335

## Postgres:
https://www.postgresql.org/docs/9.1/libpq-ssl.html#LIBPQ-SSL-PROTECTION

### Handshake
https://www.postgresql.org/docs/9.3/protocol-flow.html

1. Upon initial Dial the server waits for the client to issue a StartupMessage; This message includes the names of the user and of the database the user wants to connect to; it also identifies the particular protocol version to be used.
2. To initiate an TLS-encrypted connection, the frontend initially sends an SSLRequest message rather than a StartupMessage
3. The client sends the StartupMessage
4. The server then sends an appropriate authentication request message, to which the client must reply with an appropriate authentication response message.

### Implementation

support for "sslmode" = (
  disable
  allow
  prefer
  require
  verify-ca
  verify-full
)

### OSS libraries

+ https://github.com/lib/pq/blob/master/ssl.go
+ https://github.com/CrunchyData/crunchy-proxy/tree/master/connect

**Comment by doodlesbykumbi** [comment]
Plan is available at https://gist.github.com/doodlesbykumbi/6f02da6f2ecb66a8e6f14a3db65bbb3a

**Comment by doodlesbykumbi** [comment]
Here's the plan draft:

## TLS Support for Database Handlers

### General approach
+ Extract sslmode params from credentials into backend connection options
+ Dial backend to get net.Conn
+ Default to insecure connection, regardless of support
+ Ensure client TLS requirements match server requirements and support, FAIL if not.
  + Default to insecure connection, regardless of support
  + Use TLS if server demands it
+ Upgrade net.Conn to tls.Conn and use appropriate strategy for sslmode

### Test cases

Given db container services with TLS support and without:
+ each sslmode works or errors as intended
+ happy path to secretless via unix socket, and tcp

### TODO

+ update documentation for each db handler with descriptions of sslmode params in credentials

## MySQL
https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html#using-encrypted-connections-client-side-configuration

### Handshake

https://dev.mysql.com/doc/internals/en/connection-phase.html

Note that throughout the handshake a sequenceID is maintained which is incremented at every step. This means a handshake with TLS-encryption will have a final sequenceID higher than a plain handshake.

1. Upon initial Dial the server responds to client with capabilities
2. Client creates HandshakeResponse with capabilities in common .e.g TLS
3. To initiate an TLS-encrypted connection the client sends an SSLRequest, a truncated version of HandshakeResponse. See https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::SSLRequest
4. Finally, client sends HandshakeResponse which contains authentication information. See https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
5. Deal with Authentication Method Mismatch. See https://dev.mysql.com/doc/internals/en/authentication-method-mismatch.html

### Implementation

support for "ssl-mode" = (
  DISABLED
  PREFFERED
  REQUIRED
  VERIFY_CA
  VERIFY_IDENTITY
)

### OSS libraries

+ https://github.com/go-sql-driver/mysql/blob/master/packets.go#L322-L335

## Postgres:
https://www.postgresql.org/docs/9.1/libpq-ssl.html#LIBPQ-SSL-PROTECTION

### Handshake
https://www.postgresql.org/docs/9.3/protocol-flow.html

1. Upon initial Dial the server waits for the client to issue a StartupMessage; This message includes the names of the user and of the database the user wants to connect to; it also identifies the particular protocol version to be used.
2. To initiate an TLS-encrypted connection, the frontend initially sends an SSLRequest message rather than a StartupMessage
3. The client sends the StartupMessage
4. The server then sends an appropriate authentication request message, to which the client must reply with an appropriate authentication response message.

### Implementation

support for "sslmode" = (
  disable
  allow
  prefer
  require
  verify-ca
  verify-full
)

### OSS libraries

+ https://github.com/lib/pq/blob/master/ssl.go
+ https://github.com/CrunchyData/crunchy-proxy/tree/master/connect

**Comment by izgeri** [comment]
@doodlesbykumbi a few questions:
- can you add some examples to clarify the UX of using the handlers with SSL? I'm not sure I follow what the config changes required will look like. I am wondering if there is a way to do this so that it's even more transparent to the user (not sure if that's possible)
- can you expound on why the default is to not use SSL? tbh this surprised me, and now I'm wondering what's the standard for db client/server connections - it seems like it varies from client to client
- do you have an understanding of the specific changes that will need to be made to each handler to get this working? what I don't have from this is a clear picture of the next steps / what's missing, which makes it hard to understand scope. if you have context around this, it would be helpful to add (maybe in an additional section?). right now, most of the functionality you describe for mysql / pg already exists - so tracking where the changes are is a little tricky.
