### ISSUE TITLE
Database handlers connect to backend servers via SSL

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#50]
# Overview

GIVEN I connect to pg or MySQL via Secretless over TCP or Unix socket
THEN Secretless connects with the pg or MySQL backend by sending an an SSL request before sending the handshake response packet (for MySQL, as described in the [MySQL protocol docs](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_v10.html))

As part of this update, the disclaimer on the pg/MySQL handler pages on the website should be removed.

# Story Breakdown
- [X] Parent of #460 - A plan exists for updating the database handlers to use SSL for the backend connections

- [x] Parent of #533 - Postgres Handler supports TLS defaulting to sslmode=require
- [x] Parent of #534 - MySQL Handler supports TLS defaulting to sslmode=require

- [x] Parent of #543 - Modify demos to accommodate default TLS requirements for database handlers

- [x] Parent of #538 - MySql docs explain TLS options clearly
- [x] Parent of #537 - Postgres docs explain all TLS options clearly

- [x] Parent of #536 - Mysql handler supports sslrootcert and sslmode up to verify-ca
- [x] Parent of #535 - Postgres handler supports sslrootcert and sslmode up to verify-ca

Planned future work:
- #548 - pg / mysql handler supports sslmode=verify-full
- #549 - pg / mysql handler supports private-key pair as sslkey and sslcert

# Plan

[Downstream TLS Support for Database Handlers](https://github.com/cyberark/secretless-broker/blob/master/design/tls-support-plan.md)
