### ISSUE TITLE
Pipeline stages beyond build rely on the commit $TAG instead of latest

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#518]
Pipeline stages really shouldn't rely on `secretless-*:latest`. We'll end up with race conditions on concurrent builds. A better alternative is `secretless-*:$TAG`

- [ ] Update processes that run after the images are built to use the tagged image instead of the local `latest` image
- [ ] Update the gitlab build to use the tagged image instead of the local `latest` image
- [ ] Remove the `latest` tags from `bin/build`

**Comment by szh** [comment]
This is now handled by the auto release process
