### ISSUE TITLE
Secretless documentation moved to Flare

### ISSUE THREAD

**Issue by typaulhus** [cyberark/secretless-broker#552]
This epic focuses on the website updates needed for moving the documentation for Secretless to Flare.

- [x] Parent of #553 - Design comps for documentation homepage, subpages
- [x] Parent of #554 - secretless.io navigation is updated to reflect new docs website (we should make these changes, but hold the PR until the Flare site is ready) 
- [x] Parent of #566 - There is a subdomain for documentation with SSL
- [x] Parent of #580 - Flare draft documentation content has been cross-checked
- [x] Parent of #581 - Secretless flare documentation site has updated design
- [x] Parent of cyberark/secretless-docs#16 - Design punch list
- [x] Parent of cyberark/secretless-docs#19 - Initial documentation content matches original site
- [ ] Parent of cyberark/secretless-docs#79 - Footer links are updated
- [ ] Parent of  cyberark/secretless-docs#96 - Tutorial is removed from site

**Comment by izgeri** [comment]
@yserota I added the issues for updating the footer links and removing the tutorial from the docs site above
