### ISSUE TITLE
Secretless configuration is intuitive and simple

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#707]
ETA for completion of this epic: June 6, 2019
Confidence level of ETA accuracy: 90%
[Design document](https://github.com/cyberark/secretless-broker/blob/master/design/simpler-configuration.md)

## Link to Aha
https://cyberark.aha.io/features/AAM-92

### Secretless UX is intuitive and simple: improved secretless.yml and docs
This epic is for simplifying the user-facing experience of configuring Secretless.  It removes unnecessary concepts and presents better chrome to the user.  This improvement comes in two main flavors:

1. Shorter, simpler `secretless.yml` configuration files
2. Shorter, simpler "concept" documentation

The linked tasks break down how this will be achieved.

### Development
- [ ] Parent of #708 - Configuration parsing in config package handles new config format
- [ ] Parent of #714 - Secretless configuration syntax is versioned 

### Testing
- [ ] Parent of #712 - All Secretless test cases use new yml config format

### Documentation
- [ ] Parent of #713 - All Secretless configuration code samples are updated to reflect new yml config format
- [ ] Parent of cyberark/secretless-docs#135 - Listener / Handler references are updated to refer to single handler construct

## Additional Dev Notes

1. Open question: How should Secretless fail on invalid configuration when watching ?
2. How should authenticators handle parsing and validation of service configuration.  Idea:
    - Secretless handle the global configuration in the config package
    - Proxy delegates validation to authenticator (fail fast)
    - Proxy passes the `map[string]interface` service configuration to the authenticator
3. In implementing, multiple authenticators under http protocol (see #708)

## Future work
- We have planned future work to further simplify and improve the plugin interface. This will be done in a follow-on effort.
- Update the configuration CRD to follow the new model (#715)
- Update the configuration data structures (#710)
