### ISSUE TITLE
Secretless has an end-to-end test in a realistic environment with DAP

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#717]
## Timeline
Tests should start on this by June 3 against the latest release
Tests against the planned stable release should begin no later than June 10

## Description
In order to ensure that Secretless meets the criteria for a stable release, we would like to set up an end-to-end test that runs in a realistic environment.

The core acceptance criteria that we want to validate with this test are:
- Secretless is stable 
  - It does not randomly drop connections while running 
  - It can run without failure for an extended period of time (~4 days) 
  - It can consistently open connections while running 
  - When it fails, the pod is destroyed and rescheduled 
- Secretless is easy to set up, and setup takes less than 10 minutes 
  - This assumes DAP is already deployed and configured to use the Kubernetes authenticator - that is, "Secretless Setup" is the set of steps that the developer takes in the description below
- Secretless has minimal impact on connection speeds 
  - Request throughput is within 20% of direct-to-DB speed 
- Secretless performs under load in a realistic environment 
- Secretless handles connections transparently, so that requests from the client are appropriately transmitted to the server and messages from the server are propagated back to the client

## Test setup

We typically tell the story of deploying Secretless by breaking it into two parts - one is the system admin / operator who can set up the required infrastructure and store the necessary secrets, and one is the application developer who can deploy the app referencing the needed secrets. We'd like to run the test this way as well

### Operator Tasks
- Ensure a working OpenShift (OC) 3.9 cluster is available for deploying applications
- Deploy PostgreSQL 10.7 and MySQL 5.7 external to the OC cluster and configured with support for SSL (an example of the configuration for PostgreSQL is [here](https://secretless.io/tutorials/kubernetes/sec-admin.html))
- Deploy 10.9 DAP master external to the OC cluster and configure it for a follower in OC
- Deploy a DAP follower to OC with the Kubernetes authenticator enabled and configured
- Create one database account in each DB for application use and load the database connection information into Conjur variables

### Developer tasks
- Write the application for each database
  - The application should be set up to both continuously open connections to MySQL and PostgreSQL and to have some long-lived connections
  - The application should record any connection failures and measure performance impacts versus direct-to-DB connections **[TBD - We should have a metric for what’s acceptable]**
- Ensure that DAP is setup to authenticate the applications (eg there is a service account-type Conjur host identity defined in policy that maps to a service account in OC - an example service account host identity is [here](https://github.com/conjurdemos/kubernetes-conjur-demo/blob/master/policy/templates/project-authn-def.template.yml#L45-L49))
- Write a Secretless configuration for each application, and load into OC using ConfigMaps
- Write an application manifest for each app that includes the Secretless sidecar and mounts the config file into a volume using the ConfigMap

**Comment by izgeri** [comment]
Things that need to be done to prepare for this test:
- [ ] Write an application that can continuously open connections to the DBs via Secretless as well as leave some long-lived connections open, and record any failures. The application should also be able to retrieve DB creds from Kubernetes Secrets and open a connection and compare query times direct-to-DB versus in a connection opened via Secretless.
- [ ] Write the Secretless configuration, and prepare to load DB data into Kubernetes secrets
- [ ] Write the app manifest
- [ ] Write the policy to add the host to Conjur to enable Secretless to authenticate with Conjur
